apiVersion: apps/v1
kind: Deployment
metadata:
    name: helm-nginx-deployment
spec:
    selector:
       matchLabels:
            run: my-nginx
    replicas: 1
    template:
       metadata:
          labels:
             run: my-nginx
       spec:
          containers:
          - name: my-nginx
            image: nginx
            ports:
            - containerPort: {{ .Values.service.targetPort }}