apiVersion: v1
kind: Service
metadata:
  name: helm-nginx-service
spec:
  selector:
      run: my-nginx
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}